name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo 'Hello everyone from the pipeline!'
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: timezoneLinux

      - name: Checkout and clone repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Setup PSQL
        uses: harmon758/postgresql-action@v1
        with: 
          postgresql db: test_db
          postgresql user: mr_testerson
          postgresql password: pa55word

      - name: Test Utils and App
        run: PGDATABASE=test_db PGUSER=mr_testerson PGPASSWORD=pa55word npm test
